### ISSUE TITLE
[BUG] ImportError: cannot import name 'Settings' from 'ha_mqtt_discoverable'

### ISSUE THREAD

**Issue by RickC-I37** [unixorn/ha-mqtt-discoverable#103]
When I try to import like so:

`from ha_mqtt_discoverable import Settings, DeviceInfo`

I get the following exception:

`Exception has occurred: ImportError
cannot import name 'Settings' from 'ha_mqtt_discoverable' (/home/hanns/.local/lib/python3.9/site-packages/ha_mqtt_discoverable/__init__.py)
  File "/home/hanns/publishMqtt.py", line 3, in <module>
    from ha_mqtt_discoverable import Settings, DeviceInfo
ImportError: cannot import name 'Settings' from 'ha_mqtt_discoverable' (/home/hanns/.local/lib/python3.9/site-packages/ha_mqtt_discoverable/__init__.py)`

**Comment by kueblert** [comment]
In case you installed via pip you might want to check the installed version. On an raspberry pi with python 3.9 I had a similar problem.

**Comment by RickC-I37** [comment]
Your're right. Python 3.10 is required. Thank you!
