### ISSUE TITLE
Support Cover MQTT platform type

### ISSUE THREAD

**Issue by marleyjaffe** [unixorn/ha-mqtt-discoverable#127]
**Is your feature request related to a problem? Please describe.**
I have written a python app that interacts with a relay that controls a cover entity (gate). I would like to easily add HomeAssistant compatible MQTT into it. 

**Describe the solution you'd like**
Support Home Assistant Cover MQTT platform and all functionality: https://www.home-assistant.io/integrations/cover.mqtt/

**Describe alternatives you've considered**
Manually writing MQTT using paho

**Additional context**
Happy to implement if pointed in the right direction. Its likely easier to update this than build my own functionality in python.

**Comment by ha-enthus1ast** [comment]
@unixorn building a simple cover, ie a cover not able to report its position nor its tilt position, is quite a small task and I would be happy to help with it.
However, as some covers reports its position it would require reporting back to additional topics (and perhaps also listen on multiple command topics), at least from what I can tell from the documentation. Any ideas on how to do this without making major changes in the model?

**Comment by ha-enthus1ast** [comment]
#143 Adds basic support for cover entities

**Comment by unixorn** [comment]
Closed by #145
