### ISSUE TITLE
Please Release the current mainline to support Custom Port

### ISSUE THREAD

**Issue by unl0ck** [unixorn/ha-mqtt-discoverable#205]
**Is your feature request related to a problem? Please describe.**
Currently you are not support another Port as the default port

**Describe the solution you'd like**
8 months ago would added the custom port support

**Describe alternatives you've considered**

**Additional context**
Thanks for Creating this mega Module it made my implementation easier

**Comment by unixorn** [comment]
Forgot to close this when port support was released.
