### ISSUE TITLE
Use mqtt.publish.single to publish each message

### ISSUE THREAD

**Issue by mion00** [unixorn/ha-mqtt-discoverable#29]
**Is your feature request related to a problem? Please describe.**
I am testing the chances in #15 in one of my projects [(pergolafabio/Hikvision-Addons)](https://github.com/pergolafabio/Hikvision-Addons).
I have some callback functions that are invoked in a multi-threaded context to update various sensors.
When publishing a new state using `binary_sensor.on()` from the callback, it seems that no message is ever published to the broker, and even with a debugger I confirm that I reach the method `self.mqtt_client.publish()` of Discoverable, but nothing happens in the broker after that.
A similar problem is described here: https://stackoverflow.com/a/41334927. It seems that the mqtt client needs to run its internal `loop` to correctly function.

**Describe the solution you'd like**
As suggested in the above answer, if I use the utility method `publish.single()` the code works when updating the sensor from my callback functions:
```python
mqtt.publish.single('topic', 'state') 
```

**Comment by unixorn** [comment]
This sounds good, go for it

**Comment by mion00** [comment]
This change depends on the decision we take on #13 .
If we activate the MQTT client `loop` method inside the `Discoverable`, there is no more need for the `mqtt.publish.single` methods: they are simply a wrapper around an additional instance of MQTT client that internally run its own loop, then shut it down when returning from the call.

**Comment by unixorn** [comment]
You've done more with mqtt than I have. Do whatever you think will make using the module easier for others, I trust you.

**Comment by mion00** [comment]
Fixed by #36, now the MQTT client correctly runs its `internal loop` when a `Discoverable` is created.
