### ISSUE TITLE
[BUG] Automatic publishing to hub.docker.com doesn't work

### ISSUE THREAD

**Issue by unixorn** [unixorn/ha-mqtt-discoverable#52]
**Describe the bug**

Creating a new vD.D.D release should publish the updated docker image to hub.docker.com. v0.6.0 did not.

**Comment by mion00** [comment]
From the CI log it seems that there are missing secrets in the Github repo. I don't have permission to access those, so I can't make sure that they are present.

**Comment by unixorn** [comment]
I'll take a look at the secrets tonight.

**Comment by unixorn** [comment]
Still doesn't work.

Added the `DOCKERHUB_USERNAME` secret, I'd created `DOCKERHUB_TOKEN` when I added `PYPI_PASSWORD`.

**Comment by unixorn** [comment]
Lovely.

Docker login step:
```
Run docker/login-action@v2
Logging into Docker Hub...
Login Succeeded!
```

Build step
```
...snip a lot...
Error: buildx failed with: ERROR: failed to solve: failed to push ***/***/ha-mqtt-discoverable:latest: server message: insufficient_scope: authorization failed
```

**Comment by unixorn** [comment]
Working now. I suspect when I re-ran the failed jobs, it didn't load the latest version of `build-publish.yml`
