### ISSUE TITLE
DIsable HEALTHCHECK rule in megalinter

### ISSUE THREAD

**Issue by mion00** [unixorn/ha-mqtt-discoverable#54]
**Is your feature request related to a problem? Please describe.**
Since the Docker image does not expose a long-running service, using an `HEALTHCHECK` directive should not be required, but the linter insists on adding it.

**Additional context**
See following github action run: https://github.com/unixorn/ha-mqtt-discovery/actions/runs/4344923891/jobs/7588916880

**Comment by unixorn** [comment]
Yeah, the trivy check assumes long-running containers instead of run-and-done ones.
