### ISSUE TITLE
Rename repo to ha-mqtt-discoverable to match the module name

### ISSUE THREAD

**Issue by unixorn** [unixorn/ha-mqtt-discoverable#55]
Rename repo to ha-mqtt-discoverable to match the module name. This will require tweaking some of the badge links.

I should have fixed this long ago, and it needs fixing before too many people start using it.

@mion00 I'm going to do this in a couple hours either at lunch or after work.

**Comment by mion00** [comment]
Ok!

**Comment by unixorn** [comment]
Done.
