### ISSUE TITLE
Move cli tools to `ha-mqtt-discoverable-cli`

### ISSUE THREAD

**Issue by unixorn** [unixorn/ha-mqtt-discoverable#74]
Per #18, move the cli tools into a different module, [ha-mqtt-discoverable](https://github.com/unixorn/ha-mqtt-discoverable-cli) so python programs that only use the API don't also install all of our cli tools.

**Comment by mion00** [comment]
Sure you don't want to keep a single package? (I am thinking in term of ease of maintenance and keeping everything in check under the same code structure).
I have been playing a bit with defining the CLI as a Python extra, obtaining this: https://github.com/mion00/ha-mqtt-discovery/tree/feat/typer_boilerplate (ignore the `entities.py`, it's just some boilerplate code to get going).
`Typer` is not pulled by doing `poetry install`, so consumers of the library won't have it in their dependencies.
It must be asked for by using `poetry install --extras cli`.

**Comment by unixorn** [comment]
Maybe I'm reading this wrong, but doesn't that only affect the dependencies of the module? It won't install Typer unless you do `poetry install --extras cli`, but that doesn't stop the entrypoint scripts from being created during a `pip install`, it keeps them from working because the proper dependencies weren't installed.

Moving the cli stuff to a separate package keeps them from getting installed at all by a `pip install ha-mqtt-discoverable` so that people only interested in using the module won't have the CLI tools pollute their disk.

If there's a clean way to keep both modules in the same repo I'd prefer to do that, but I don't see a way to have the cli tools currently defined in the `[tool.poetry.scripts]` section only get installed when the cli extra gets installed.

I'd be happy to be wrong though.

**Comment by mion00** [comment]
From what I learned the scripts section cannot be made conditional.
The way httpx handles it is that they always install the script entrypoint, and in that script they check if the cli dependencies are installed, otherwise they error out.

**Comment by unixorn** [comment]
Closed by https://github.com/unixorn/ha-mqtt-discoverable-cli/pull/2
